// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stockwatch.Model;

#nullable disable

namespace Stockwatch.Model.Migrations
{
    [DbContext(typeof(StockwatchDbContext))]
    [Migration("20231225020113_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Stockwatch.Model.StockAlertRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockSymbolId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UpperLimit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockSymbolId")
                        .IsUnique();

                    b.ToTable("StockAlertRanges");
                });

            modelBuilder.Entity("Stockwatch.Model.StockSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SymbolName")
                        .IsUnique();

                    b.ToTable("StockSymbols");
                });

            modelBuilder.Entity("Stockwatch.Model.StockAlertRange", b =>
                {
                    b.HasOne("Stockwatch.Model.StockSymbol", "StockSymbol")
                        .WithMany()
                        .HasForeignKey("StockSymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockSymbol");
                });
#pragma warning restore 612, 618
        }
    }
}
